import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { UserProvider } from "@/context/testContext";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Диплом",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <div className="flex flex-col">
            {/* <Navbar /> */}
            {children}
          </div>
        </UserProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
